services:
#    arnold_competences.example:
#        class: Arnold\CompetencesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    arnold_competences.admin.competences:
        class: Arnold\CompetencesBundle\Admin\CompetencesAdmin
        arguments: [~, Arnold\CompetencesBundle\Entity\Competences, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Competences }
        public: true
