<?php

namespace Arnold\ActualitesBundle\Repository;

/**
 * ActualitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualitesRepository extends \Doctrine\ORM\EntityRepository
{
    public function recentActu($limit=3)
    {
        $query = $this->createQueryBuilder("s")
                    ->orderBy('s.publishat', "DESC")
                    ->SetMaxResults($limit)
                    ->getQuery()
                    ;
        return $query->getResult(); 
    }
}
