<?php

namespace Arnold\RealisationBundle\Repository;

/**
 * RealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends \Doctrine\ORM\EntityRepository
{
    public function recentcategorie($limit=3, $id)
    {
        $query = $this->createQueryBuilder("s")
                    ->andWhere('s.categorie = :id')
                    ->setParameter('id', $id)
                    ->orderBy('s.daterealisation', "DESC")
                    ->SetMaxResults($limit)
                    ->getQuery() 
                    ;
        return $query->getResult();  
    } 
    
    public function queryallchildrenhome($id)
    {
        $query = $this->createQueryBuilder("c")
            ->andwhere("c.parents = :id")
            ->setParameter('id', $id)
            ->getQuery()
        ;
        return $query->getResult(); 

    }

    public function queryallparentshome()
    {
        $query = $this->createQueryBuilder("c")
            ->andwhere("c.parents IS NULL")
            ->getQuery()
        ;
        return $query->getResult();

    }

}
