services:
#    arnold_commentaire.example:
#        class: Arnold\CommentaireBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    arnold_commentaire.admin.commentaire:
        class: Arnold\CommentaireBundle\Admin\CommentaireAdmin
        arguments: [~, Arnold\CommentaireBundle\Entity\Commentaire, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Commentaire }
        public: true
