<?php

namespace Arnold\CommentaireBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. 
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function recentActu($limit=3, $id)
    {
        return $this->createQueryBuilder("u")
                    ->andwhere('u.actualites =:id')
                    ->setParameter('id',$id)
                    ->orderBy('u.publishat', "DESC")
                    ->SetMaxResults($limit)
                    ;  
    }

    public function recentRealisation($limit=3, $id)
    {
        return $this->createQueryBuilder("d")
                    ->andwhere('d.realisation =:id')
                    ->setParameter('id',$id)
                    ->orderBy('d.daterealisation ', "DESC")
                    ->SetMaxResults($limit) 
                    ;
    } 

    public function getAllAtualites($id)
    {
        $query = $this->createQueryBuilder("t")
                    ->andwhere('t.Atualites =:id')
                    ->setParameter('id',$id)
                    ->orderBy('t.publishat ', "DESC")
                    ->getQuery() 
                    ;
        return $query->getResult();
    }
    
    public function getAllRealisation($id)
    {
        $query = $this->createQueryBuilder("r")
                    ->andwhere('r.realisation =:id')
                    ->setParameter('id',$id)
                    ->orderBy('r.daterealisation ', "DESC")
                    ->getQuery() 
                    ;
        return $query->getResult();
    }

}
