<?php

namespace Arnold\ServiceBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryallParents()
    {
        return $this->createQueryBuilder("a")
                    ->andwhere("a.parents IS NULL"); 
    }

    public function recentService($limit=3) 
    {
        $query = $this->createQueryBuilder("d")
                    ->orderBy('d.createdat', "DESC")
                    ->SetMaxResults($limit)
                    ->getQuery()
                    ;
        return $query->getResult();  
    } 

    public function queryallchildrenhome($id)
    {
        $query = $this->createQueryBuilder("c")
            ->andwhere("c.parents = :id")
            ->setParameter('id', $id)
            ->getQuery()
        ;
        return $query->getResult();

    }

    public function queryallparentshome()
    {
        $query = $this->createQueryBuilder("c")
            ->andwhere("c.parents IS NULL")
            ->getQuery()
        ;
        return $query->getResult();

    }
}
