<?php

namespace Brice\MesMenusBundle\Repository;

/**
 * contactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactsRepository extends \Doctrine\ORM\EntityRepository
{
}
